In [4]:
import numpy as np

In [6]:
#ex1



tableau=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
a=tableau.tolist()

In [8]:
tableau

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [9]:
a

[[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]]

In [11]:
#ex3

AttributeError: 'list' object has no attribute 'dtype'

In [24]:
tableau=np.array([[1,2],[3,5]])
tableau
    


    
    

array([[1, 2],
       [3, 5]])

In [30]:
x=3
print (tableau[tableau>=x])

[3 5]


In [32]:
A=np.array([1,2])
B=np.array([3,4])
C=A+B

In [33]:
C

array([4, 6])

In [4]:
#ex5
import numpy as np
tableau=np.array([[100,200],[300,400]])
for i in range(2):
    y=np.mean(tableau[i])
    print(y)

150.0
350.0
